//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteSellingSuitcases.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tBlog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tBlog()
        {
            this.Reviews = new HashSet<Review>();
        }
    
        public int Blog_ID { get; set; }
        public string TieuDe { get; set; }
        public string TomTat { get; set; }
        public string ChiTiet { get; set; }
        public Nullable<int> MaLoaiBlog { get; set; }
        public string AnhBlog { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<int> LuotXem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual tLoaiBlog tLoaiBlog { get; set; }
        public virtual tNhanVien tNhanVien { get; set; }
    }
}
