//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteSellingSuitcases.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDinhKemSP
    {
        public int MaDK { get; set; }
        public string MaSP { get; set; }
        public string Dummy { get; set; }
    
        public virtual tDanhMucSP tDanhMucSP { get; set; }
        public virtual tDinhKem tDinhKem { get; set; }
    }
}
