//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteSellingSuitcases.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tHoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tHoaDon()
        {
            this.tChiTietHoaDons = new HashSet<tChiTietHoaDon>();
        }
    
        public int SoHD { get; set; }
        public Nullable<System.DateTime> NgayBan_NgayNhap { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<bool> Loai { get; set; }
        public string NoiDung { get; set; }
        public Nullable<bool> Ship { get; set; }
        public Nullable<int> XacNhan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tChiTietHoaDon> tChiTietHoaDons { get; set; }
        public virtual tKhachHang tKhachHang { get; set; }
        public virtual tNhanVien tNhanVien { get; set; }
    }
}
