//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteSellingSuitcases.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tYeuThich
    {
        public string MaSP { get; set; }
        public int MaKH { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
    
        public virtual tDanhMucSP tDanhMucSP { get; set; }
        public virtual tKhachHang tKhachHang { get; set; }
    }
}
